include(${CMAKE_CURRENT_LIST_DIR}/../seL4/tools/helpers.cmake)
cmake_script_build_kernel()

set(KernelPlatform "pc99" CACHE STRING "")
set(KernelSel4Arch "x86_64" CACHE STRING "")
set(KernelVerificationBuild OFF CACHE BOOL "")
set(KernelMaxNumNodes "8" CACHE STRING "")
set(KernelOptimisation "-O2" CACHE STRING "")
set(KernelRetypeFanOutLimit "256" CACHE STRING "")
set(KernelBenchmarks "none" CACHE STRING "")
set(KernelDangerousCodeInjection OFF CACHE BOOL "")
set(KernelFastpath ON CACHE BOOL "")
# set(KernelExceptionFastpath ON CACHE BOOL "")
set(KernelPrinting ON CACHE BOOL "")
set(KernelFSGSBase "inst" CACHE STRING "")
# set(KernelMultiboot1Header OFF CACHE BOOL "")
# set(KernelMultiboot2Header OFF CACHE BOOL "")
set(KernelSupportPCID OFF CACHE BOOL "")
set(KernelVTX ON CACHE BOOL "")
set(KernelX86_64VTX64BitGuests ON CACHE BOOL "")
set(KernelSkimWindow OFF CACHE BOOL "")
set(KernelRootCNodeSizeBits "16" CACHE STRING "")
set(KernelXSaveFeatureSet "7" CACHE STRING "")
set(KernelXSaveSize "832" CACHE STRING "")
