[env]
RUST_TARGET_PATH = { value = "support/targets", relative = true }
SEL4_PREFIX = { value = "kbuild/install", relative = true }

[build]
target = "x86_64-sel4"

[unstable]
unstable-options = true
bindeps = true
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
